### ISSUE TITLE
sorting doesn't work

### ISSUE THREAD

**Issue by tombohub** [bmihelac/ra-data-django-rest-framework#15]
When click to sort, arrow appears. but nothing else happens.

Anybody has same issue?

**Comment by krishnaghatti** [comment]
Hi @tombohub I hope you have added the filter backend for the viewset. I have the below config and the sorting works just fine. I hope. this helps.
```
filter_backends = [filters.OrderingFilter]
ordering = ['id']
```

**Comment by tombohub** [comment]
Yes it works now.

So it orders by sending url parameters. Is that how usually these tables work? Material UI data table?

**Comment by krishnaghatti** [comment]
> So it orders by sending url parameters. Is that how usually these tables work? Material UI data table?
It uses the ordering field in the query that is sent to the backend. You can check the same in your backed logs. Below are queries that are sent to the backend when using the sort option. 
```
GET /api/countries/?ordering=id&page=1&page_size=10
GET /api/countries/?ordering=name&page=1&page_size=10 
```

**Comment by tombohub** [comment]
I see it fetches every time it sorts? ok
