### ISSUE TITLE
Are you interested in a token provider based on `djangorestframework-simplejwt`?

### ISSUE THREAD

**Issue by barseghyanartur** [bmihelac/ra-data-django-rest-framework#34]
Are you interested in a token provider based on [djangorestframework-simplejwt](https://github.com/jazzband/djangorestframework-simplejwt)?

**Comment by bmihelac** [comment]
Hi @barseghyanartur, yes, jwt would be a good addition. As a note, I am currently not actively working on this project.

**Comment by barseghyanartur** [comment]
@bmihelac:

I'm not actively working on any of mine too. :) Just trying to be helpful. I was already pleased to discover react-admin which made my day by allowing me to implement the desired features within no time. I then discovered this package and was happy to throw away some of my code in favor of what you have made. Thus, many thanks!

**Comment by sheriffdeen-yusuf** [comment]
> Hi @barseghyanartur, yes, jwt would be a good addition. As a note, I am currently not actively working on this project.

Hello @bmihelac, sincerely appreciate your tremendous effort and other contributors on this framework. I had issues following up with the example, a console error pops up; host:3000 can't access host:8000. I'd sincerely appreciate any help on how to properly connect my react-admin to Django rest-api.

Thanks.

**Comment by barseghyanartur** [comment]
@sheriffdeen-yusuf:

Demo of this project worked for me out of the box. Follow the instructions in the docs.

**Comment by barseghyanartur** [comment]
PR accepted and merged into the master.
