### ISSUE TITLE
Cannot read properties of undefined (reading 'id') after deleteMany

### ISSUE THREAD

**Issue by e-stepanov** [bmihelac/ra-data-django-rest-framework#49]
Handling of the server response in the `deleteMany` method expects json with id field but django rest framework returns response without body.

[According](https://marmelab.com/react-admin/DataProviders.html#response-format) to react-admin docs the ids of the deleted records are optional in deleteMany. So that an empty array can be returned as a `data` value.

I can create a pull request if you confirm this bug.

**Comment by bmihelac** [comment]
@e-stepanov thanks for this issue report. I am currently involved in other projects, and cannot devote time to ra-data-django-rest-framework but would be glad to merge a pull request.

**Comment by e-stepanov** [comment]
Done! Will you release a new version with this fix?

**Comment by bmihelac** [comment]
@e-stepanov thanks for PR, it is in 0.2.1
