### ISSUE TITLE
Create, Update data provider use get instead of post or patch

### ISSUE THREAD

**Issue by JasurN** [bmihelac/ra-data-django-rest-framework#5]
Hello. Thank you very much for such a project. I was testing and in the example, when I create a new post, the data provider sends a get request to the backend. Is this problem of data provider? You can see this problem when you create new post in example. Thank you
![image](https://user-images.githubusercontent.com/23478773/86260122-4bf58b00-bbd6-11ea-9671-5d0ca8f60637.png)

**Comment by JasurN** [comment]
Now I updated source code with the latest commit https://github.com/bmihelac/ra-data-django-rest-framework/commit/e51f17e75219301a3e18d80d453f87d8860e570e. Now it is working as intended.

**Comment by bmihelac** [comment]
@JasurN good news :) I am closing issue
